# -*- coding: utf-8 -*-
"""Check_New.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRIbvK21zYx4b1ScoKt5skmjP29jm7ql

#  **ICT303 - Assignment 2**

**Your name:**

**Student ID: **

**Email: **

In this assignment, you will build and train a deep learning model for solving a problem of your choice.


You are required to:
- Think of a practical problem that you would like to solve. The problem can be related, but not limted to, object detection and recognition from images, text analysis, speech analysis, image unpainting, converting images to artistic painting, action recognition (from images or videos), image to text (i.e., generating textual description for images or videos), or texrt to image (generating images from text) etc.,
- Find an appropriate data set to train and test the model you will develop. Note that the dataset should contain enough data (with groundtruth labels) so that when used for training, the model can generalize well to unseen data.
- Design a neural network that will solve the problem
- Train the neural network on your training data and then evaluate its performance on test data
- Analyze the performance of the network you developed and discuss its limitations.

**What to submit:**
- A colab notebook that describes:
 - The problem you would like to solve **[10 Marks]**
 - The dataset that you will use to train and test the deep learning model that you will develop **[10 marks]**
 - A diagram that describes the architecture of the neural network that you developed **[10 marks]**
 - Performance curves - this is includes the loss curves as well as the accuracy **[10 marks]**
 - A discussion, analysis and justification of the different choices you made and their effect on the performance **[15 marks]**
 - A discussion, analysis of the limitations of your method. You can also show failure cases and try to understand why did it fail on these cases **[15 marks]**

- Source code that runs - this includes both code for training and testing **[30 marks]**

You also need to submit the dataset you used for training and testing, or alternatively provide the code that downloads the data.

Make sure you reference all sources from which you took information.

You are allowed to use existing neural networks (not required to implement them from scratch). But, you must customize the architecture to the problem you want to solve.

**Where to find datasets?**
- [Kaggle competition](https://www.kaggle.com/c/dog-breed-identification) is a good source.
- You can also look at this [wikipedia site[(https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research)

If you are thinking of a specific problem and were unable to find a suitable dataset, please talk to me during the lecture or lab and we will search together.

**Recommended timeline**
- Week 1 of Assignement release: identify 2 or 3 problems of interest, a find dataset for each of the problem and try to understand how to load the data and how it is organised. Discuss it with the UC during the lab session or via email.
- Week 2:
 - Make sure your dataloader works proply and you are able to load the data and structure it in a way that neural networks can use them.
 - Design your network architecture
- Week 3: Network architecture implemented and training and testing done. Evaluate the performance
- Week 4: Finetune the network architecture and the hyperparameters to improve the performance. Write the report for submission.

It is highly recommended that you follow this timeline. The earlier you start training and testing, the more time you will have to finetune your solution and achieve a better performance.

**Problem Definition**

**Objective**: Classify movie reviews as positive or negative using text data from the IMDb Movie Reviews dataset.

**Output**: A trained deep learning model that predicts the sentiment (positive or negative) for a given text.

People post reviews on IMDb titles on a large scale. To get an idea about movies based on text content review would take a huge amount of time to go through the large paragraphs. Automating the labeling of reviews to be good/bad is the best way to get an overall idea. This research problem targets to solve this issue using a deep learning approach.

### Step 1: Downloading and Extracting the IMDb Dataset
The IMDb Movie Reviews dataset is downloaded from Stanford's website. The dataset contains two main folders, 'train' and 'test', each having two subfolders, 'pos' and 'neg', representing positive and negative reviews.
"""

import requests

# Download the dataset
url = 'https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz'
response = requests.get(url)

# Save the file
with open('aclImdb_v1.tar.gz', 'wb') as f:
    f.write(response.content)

# Optionally, you can extract it if you need to
import tarfile

# Extract the tar.gz file
with tarfile.open('aclImdb_v1.tar.gz', 'r:gz') as tar:
    tar.extractall()  # Extract to the current directory


import tarfile

# Step 2: Extract the dataset
with tarfile.open('aclImdb_v1.tar.gz', 'r:gz') as tar:
    tar.extractall()  # Extract to the current directory

# Step 3: Check the structure of the dataset
import os

# List the contents of the aclImdb directory
print("Contents of aclImdb:")
print(os.listdir('aclImdb'))

# List the contents of the train folder
print("\nContents of aclImdb/train:")
print(os.listdir('aclImdb/train'))


"""Instead of uploading downloaded dataset again and again throughout the research, this way it is downloaded at the runtime into the host.

### Downloading GloVe Embeddings

In this step, we will download the GloVe (Global Vectors for Word Representation) embeddings, which provide pre-trained word vectors that capture semantic relationships between words. Using GloVe embeddings can enhance the performance of our model by supplying it with rich contextual information about the language used in movie reviews.

We will download the embeddings from the Stanford NLP website and extract the contents for further use in our model. The embeddings will help improve the model's ability to understand and classify sentiments in the text data more effectively.
"""

import requests
import zipfile
import os

# URL for the GloVe embeddings
url = 'http://nlp.stanford.edu/data/glove.6B.zip'

# Download the GloVe embeddings
response = requests.get(url)

# Save the file
with open('glove.6B.zip', 'wb') as f:
    f.write(response.content)

# Extract the zip file
with zipfile.ZipFile('glove.6B.zip', 'r') as zip_ref:
    zip_ref.extractall('glove_embeddings')  # Specify the directory to extract to

# Optionally, remove the zip file after extraction
os.remove('glove.6B.zip')


"""### Dataset Overview

The IMDb Movie Reviews dataset is used to train and evaluate our sentiment classification model. It consists of **train** and **test** datasets, each containing review texts with sentiment labels.

#### Dataset Structure
- **Train and Test Folders**:
  - Divided into 'train' and 'test' folders, each with 'pos' (positive) and 'neg' (negative) subfolders.
  - Reviews are labeled as 1 for positive and 0 for negative.
  - Both datasets contain **25,000 entries** each, with **12,500 positive** and **12,500 negative** reviews.
  - The equal distribution ensures no **class imbalance**, aiding model generalization. For more on class imbalance, refer to [this article](https://medium.com/metaor-artificial-intelligence/solving-the-class-imbalance-problem-58cb926b5a0f).

#### Review Length Analysis
Review lengths vary significantly, and understanding these statistics aids in model design and tokenization.

##### Training Dataset Review Length Statistics
| Statistic      | Value        |
|----------------|--------------|
| Minimum        | 10 words     |
| Maximum        | 2,470 words  |
| Average        | 233.79 words |
| Median (Q2)    | 174 words    |
| First Quartile (Q1) | 127 words |
| Third Quartile (Q3)  | 284 words |

##### Test Dataset Review Length Statistics
| Statistic      | Value        |
|----------------|--------------|
| Minimum        | 4 words      |
| Maximum        | 2,278 words  |
| Average        | 228.53 words |
| Median (Q2)    | 172 words    |
| First Quartile (Q1) | 126 words |
| Third Quartile (Q3)  | 277 words |

#### Word Correlation with Sentiment
Certain words frequently appear in positive reviews, indicating a strong correlation with positive sentiment, such as:
- **great**, **excellent**, **best**, **wonderful**, **love**, **perfect**, **well**, **amazing**

This overview provides a clear understanding of the dataset's structure and characteristics, laying a solid foundation for effective model training.

### Step 2: Loading Data into Variables
The `load_imdb_data` function reads positive and negative reviews from the training and test directories, converting them into text data and labels.
- **Labels**: 1 for positive and 0 for negative.
- The dataset is divided into training and test sets.
"""

import os
import numpy as np

def load_imdb_data(data_dir):
    labels = []
    texts = []

    # Load positive reviews
    pos_dir = os.path.join(data_dir, 'pos')
    for filename in os.listdir(pos_dir):
        with open(os.path.join(pos_dir, filename), 'r', encoding='utf-8') as f:
            texts.append(f.read())
        labels.append(1)

    # Load negative reviews
    neg_dir = os.path.join(data_dir, 'neg')
    for filename in os.listdir(neg_dir):
        with open(os.path.join(neg_dir, filename), 'r', encoding='utf-8') as f:
            texts.append(f.read())
        labels.append(0)

    return np.array(texts), np.array(labels)

# Load train and test data
train_data_dir = 'aclImdb/train'
test_data_dir = 'aclImdb/test'

train_texts, train_labels = load_imdb_data(train_data_dir)
test_texts, test_labels = load_imdb_data(test_data_dir)

print(f"Loaded {len(train_texts)} training samples and {len(test_texts)} test samples.")

train_texts

train_labels

# Print some sample reviews and their corresponding labels
for i in range(3):  # Print first 3 samples
    print(f"Sample {i+1}:")
    print(f"Review: {train_texts[i]}")
    print(f"Label (1=Positive, 0=Negative): {train_labels[i]}")
    print("\n" + "-"*80 + "\n")

"""### Step 3: Exploratory Data Analysis (EDA)
We perform basic EDA to calculate statistics for both training and test datasets, such as:
- Number of samples
- Average review length (in words)
- Number of positive and negative reviews

This helps us understand the dataset structure and check for any class imbalance.

"""

# Basic statistics about the dataset
def dataset_statistics(texts, labels, dataset_type="Training"):
    num_samples = len(texts)
    avg_length = np.mean([len(text.split()) for text in texts])
    num_positive = np.sum(labels)
    num_negative = len(labels) - num_positive

    print(f"{dataset_type} Dataset Statistics:")
    print(f"Number of samples: {num_samples}")
    print(f"Average review length: {avg_length:.2f} words")
    print(f"Number of positive reviews: {num_positive}")
    print(f"Number of negative reviews: {num_negative}")
    print("-" * 50)

# Calculate statistics for training and test datasets
dataset_statistics(train_texts, train_labels, "Training")
dataset_statistics(test_texts, test_labels, "Test")

"""### Step 4: Data Visualization
The following visualizations help us understand the dataset better:
- **Label Distribution**: Bar plots show the distribution of positive and negative reviews.
- **Review Length Distribution**: Histograms show the variation in review lengths.

"""

import matplotlib.pyplot as plt

# Plot label distribution for both training and test datasets
def plot_label_distribution(labels, dataset_type="Training"):
    pos_count = np.sum(labels)
    neg_count = len(labels) - pos_count

    plt.figure(figsize=(6, 4))
    plt.bar(['Positive', 'Negative'], [pos_count, neg_count], color=['green', 'red'])
    plt.title(f'{dataset_type} Dataset Label Distribution')
    plt.ylabel('Number of Reviews')
    plt.show()

# Plot for training and test sets
plot_label_distribution(train_labels, "Training")
plot_label_distribution(test_labels, "Test")

"""### Plotting Review Length Distribution



"""

# Plot review length distribution
def plot_review_length_distribution(texts, dataset_type="Training"):
    review_lengths = [len(text.split()) for text in texts]

    plt.figure(figsize=(8, 6))
    plt.hist(review_lengths, bins=30, color='blue', alpha=0.7)
    plt.title(f'{dataset_type} Dataset Review Length Distribution')
    plt.xlabel('Review Length (in words)')
    plt.ylabel('Number of Reviews')
    plt.show()

# Plot review length distribution for training set
plot_review_length_distribution(train_texts, "Training")

"""# Review Length Statistics For Training and Testing"""

import numpy as np

# Function to calculate and print review length statistics
def review_length_stats(texts, dataset_type="Training"):
    review_lengths = np.array([len(text.split()) for text in texts])

    # Calculate stats
    min_length = np.min(review_lengths)
    max_length = np.max(review_lengths)
    avg_length = np.mean(review_lengths)
    median_length = np.median(review_lengths)
    q1 = np.percentile(review_lengths, 25)
    q3 = np.percentile(review_lengths, 75)

    # Print stats
    print(f"{dataset_type} Dataset Review Length Statistics:")
    print(f"Minimum review length: {min_length} words")
    print(f"Maximum review length: {max_length} words")
    print(f"Average review length: {avg_length:.2f} words")
    print(f"Median review length (Q2): {median_length} words")
    print(f"First Quartile (Q1): {q1} words")
    print(f"Third Quartile (Q3): {q3} words")
    print("-" * 50)

# Calculate and print review length statistics for the training and test datasets
review_length_stats(train_texts, "Training")
review_length_stats(test_texts, "Test")

"""### Step 5: TF-IDF Feature Analysis

This step converts review texts into **TF-IDF vectors**, highlighting important words based on their frequency and uniqueness.

- **Purpose**: To identify words that are strongly associated with positive or negative sentiments.
- **Process**: We use up to 1,000 TF-IDF features and calculate the correlation of each word with sentiment labels.
- **Output**: Top 10 words positively and negatively correlated with positive sentiment.

This helps understand which words contribute most to sentiment classification.

"""

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# Convert texts to TF-IDF features
vectorizer = TfidfVectorizer(max_features=1000)  # Limit to 1000 features for simplicity
train_tfidf = vectorizer.fit_transform(train_texts)

# Convert to a DataFrame for easier analysis
train_tfidf_df = pd.DataFrame(train_tfidf.toarray(), columns=vectorizer.get_feature_names_out())

# Add the labels as a new column
train_tfidf_df['label'] = train_labels

# Calculate correlation between each word's TF-IDF score and the labels
correlations = train_tfidf_df.corr()['label'].sort_values(ascending=False)

# Print top positive and negative correlated words
print("\nTop 10 positively correlated words with positive sentiment:")
print(correlations.head(10))

print("\nTop 10 negatively correlated words with positive sentiment:")
print(correlations.tail(10))

"""### Step 6: Text Tokenization and Padding
The text data is tokenized to convert words into numerical sequences, making them compatible with the neural network. The sequences are then padded to ensure uniform input length.
- **Max words considered**: 10,000
- **Max sequence length**: 256 words
- **Embedding dimension**: 100

"""

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Parameters
max_words = 10000  # Only consider the top 10,000 words in the dataset
max_len = 256      # Max review length in words
embedding_dim = 100  # Dimension for word embeddings

# Tokenize the text data
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(train_texts)

# Convert texts to sequences of integers
train_sequences = tokenizer.texts_to_sequences(train_texts)
test_sequences = tokenizer.texts_to_sequences(test_texts)

# Pad the sequences to ensure uniform input length
train_data = pad_sequences(train_sequences, maxlen=max_len)
test_data = pad_sequences(test_sequences, maxlen=max_len)

# Convert labels to numpy arrays
train_labels = np.array(train_labels)
test_labels = np.array(test_labels)

print(f"Shape of train data: {train_data.shape}")
print(f"Shape of test data: {test_data.shape}")

"""### Loading GloVe Embeddings

In this step, we load the GloVe embeddings from the downloaded file. The embeddings will provide pre-trained word vectors that enhance the model's understanding of the semantic relationships between words.

We prepare an embedding matrix where each row corresponds to a word in our tokenizer's vocabulary. This matrix will be used in our model to replace the default embedding layer, improving performance by leveraging rich contextual information.

"""

# Load GloVe embeddings
import os
import urllib.request
import zipfile
import numpy as np

# Step 1: Download GloVe embeddings
glove_url = 'http://nlp.stanford.edu/data/glove.6B.zip'
glove_zip_path = 'glove.6B.zip'

# Download the GloVe zip file if it does not exist
if not os.path.isfile(glove_zip_path):
    print(f"Downloading GloVe embeddings from {glove_url}...")
    urllib.request.urlretrieve(glove_url, glove_zip_path)

# Step 2: Extract GloVe embeddings
with zipfile.ZipFile(glove_zip_path, 'r') as zip_ref:
    zip_ref.extractall()  # Extract to the current directory

# Load GloVe embeddings
embedding_index = {}
embedding_dim = 100  # You can adjust this based on which file you want to use
glove_file_path = f'glove.6B.{embedding_dim}d.txt'  # Ensure the filename matches the dimension

# Ensure the GloVe file exists before attempting to load
if os.path.isfile(glove_file_path):
    with open(glove_file_path, encoding='utf-8') as f:
        for line in f:
            values = line.split()
            word = values[0]
            coefs = np.asarray(values[1:], dtype='float32')
            embedding_index[word] = coefs

    print(f"Loaded {len(embedding_index)} word vectors.")

    # Prepare embedding matrix
    max_words = 10000  # Set this based on your tokenizer's configuration
    embedding_matrix = np.zeros((max_words, embedding_dim))
    
    # Assuming 'tokenizer' is defined elsewhere in your code
    for word, i in tokenizer.word_index.items():
        if i < max_words:
            embedding_vector = embedding_index.get(word)
            if embedding_vector is not None:
                embedding_matrix[i] = embedding_vector
else:
    print(f"Error: {glove_file_path} does not exist.")


"""### Step 7: Neural Network Architecture
An LSTM-based neural network is designed to classify movie reviews:
- **Embedding Layer**: Converts word indices to dense vectors.
- **LSTM Layer**: Captures long-term dependencies in text sequences.
- **GlobalMaxPooling1D**: Reduces the sequence length by selecting the most important features.
- **Dense Layer**: Applies ReLU activation to capture non-linearity.
- **Dropout Layer**: Regularizes the network by randomly dropping neurons during training.
- **Output Layer**: Uses sigmoid activation for binary classification.

"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, GlobalMaxPooling1D
from tensorflow.keras.regularizers import l2

model = Sequential([
    Embedding(input_dim=max_words,
              output_dim=embedding_dim,
              input_length=max_len,
              weights=[embedding_matrix],
              trainable=False),  # Use the GloVe-based embedding layer
    Bidirectional(LSTM(128, return_sequences=True)),  # Change to Bidirectional LSTM
    GlobalMaxPooling1D(),
    Dense(64, activation='relu', kernel_regularizer=l2(0.001)),  # Add L2 regularization
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Print model summary
model.summary()

"""### Step 7: Model Training
The model is trained using the following parameters:
- **Epochs**: 10
- **Batch size**: 64
- **Validation split**: 20% of the training data is used for validation
The model's performance is tracked for both training and validation data.

"""

# Train the model
history = model.fit(
    train_data, train_labels,  # Training data and labels
    epochs=10,                  # Number of epochs to train for
    batch_size=64,             # Batch size for training
    validation_split=0.2,      # Use 20% of the training data for validation
    verbose=1                  # Print progress
)

"""### Step 8: Model Evaluation
The trained model is evaluated on the test set to calculate accuracy and loss:
- **Test accuracy**: Measures the model's performance on unseen data.
- **Test loss**: Reflects the difference between predicted and actual sentiment labels.

"""

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(test_data, test_labels)

print(f"Test Accuracy: {test_acc:.4f}")
print(f"Test Loss: {test_loss:.4f}")

"""Test Accuracy: 0.8898

Test Loss: 0.3585

### Step 9: Plotting Accuracy and Loss Curves
The training and validation accuracy/loss curves are plotted to visualize the model's learning process over epochs. These plots help us identify potential overfitting or underfitting.
"""

import matplotlib.pyplot as plt

# Plot the accuracy curves
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Plot the loss curves
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.show()

"""### Visualizing Model Architecture

We generate a diagram of the neural network architecture to visualize its structure, including layer shapes and names. This helps in understanding how data flows through the model.

"""

from tensorflow.keras.utils import plot_model
from IPython.display import Image

# Generate and save the model architecture diagram
plot_model(model, to_file='model.png', show_shapes=True, show_layer_names=True)

# Display the diagram in the notebook
Image('model.png')

"""### Enhancing Regularization with Dropout Adjustment

In this step, we define a new model architecture that incorporates increased dropout rates to combat overfitting.

**Key Changes**:
- **Bidirectional LSTM**: This model utilizes a Bidirectional LSTM layer to improve context understanding by processing the input sequence in both forward and backward directions.
- **Dropout Layers**: We have added a dropout layer after the LSTM layer and another before the output layer. This adjustment aims to reduce overfitting by randomly setting a fraction of the input units to zero during training, making the model more robust.
- **L2 Regularization**: Applied to the dense layer, this helps prevent the model from learning overly complex patterns in the training data.

These enhancements are designed to improve the model's generalization to unseen data while maintaining performance.

"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, GlobalMaxPooling1D, Dense, Dropout
from tensorflow.keras.regularizers import l2

# Define the model with Bidirectional LSTM
model_dropout_adjestment  = Sequential([
    Embedding(input_dim=max_words,
              output_dim=embedding_dim,
              input_length=max_len),  # GloVe embeddings not used in this model
    Bidirectional(LSTM(128, return_sequences=True)),  # Use Bidirectional LSTM for enhanced context understanding
    Dropout(0.5),  # Dropout after LSTM to reduce overfitting
    GlobalMaxPooling1D(),
    Dense(64, activation='relu', kernel_regularizer=l2(0.001)),  # Add L2 regularization
    Dropout(0.5),  # Additional dropout layer before output
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model_dropout_adjestment .compile(optimizer='adam',
                            loss='binary_crossentropy',
                            metrics=['accuracy'])

# Print model summary
model_dropout_adjestment .summary()

"""# Train Model"""

# Train the model
history = model_dropout_adjestment.fit(
    train_data, train_labels,  # Training data and labels
    epochs=10,                  # Number of epochs to train for
    batch_size=64,             # Batch size for training
    validation_split=0.2,      # Use 20% of the training data for validation
    verbose=1                  # Print progress
)

"""#Model Evaluation"""

# Evaluate the model on the test set
test_loss_2, test_acc_2 = model_dropout_adjestment.evaluate(test_data, test_labels)

print(f"Test Accuracy: {test_acc_2:.4f}")
print(f"Test Loss: {test_loss_2:.4f}")

"""### L2 Regularization with Bidirectional LSTM

**L2 Regularization**, also known as **weight decay**, adds a penalty to the loss function based on the magnitude of the weights. This technique helps prevent overfitting by discouraging the model from learning excessively large weights, which can lead to complex and less generalizable models.

#### Key Changes:
- L2 regularization is applied to both the **Bidirectional LSTM** and **Dense** layers in the model.
- This approach encourages the model to maintain smaller weights, thereby enhancing generalization and reducing the risk of overfitting.

By incorporating L2 regularization, the model becomes more robust and demonstrates improved performance on unseen data, ensuring better classification accuracy for sentiment analysis.

"""

from tensorflow.keras.regularizers import l2
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, GlobalMaxPooling1D, Dense, Dropout

# Build the model with L2 regularization and Bidirectional LSTM
model_with_l2 = Sequential([
    Embedding(input_dim=max_words,
              output_dim=embedding_dim,
              input_length=max_len),
    Bidirectional(LSTM(128, return_sequences=True, kernel_regularizer=l2(0.001))),  # Bidirectional LSTM with L2 regularization
    GlobalMaxPooling1D(),  # Global max pooling layer
    Dense(64, activation='relu', kernel_regularizer=l2(0.001)),  # Dense layer with L2 regularization
    Dropout(0.5),  # Dropout for regularization
    Dense(1, activation='sigmoid')  # Output layer with sigmoid activation for binary classification
])

# Compile the model
model_with_l2.compile(optimizer='adam',
                                     loss='binary_crossentropy',
                                     metrics=['accuracy'])

# Print model summary
model_with_l2.summary()

# Train the model
history = model_with_l2.fit(
    train_data, train_labels,  # Training data and labels
    epochs=10,                  # Number of epochs to train for
    batch_size=64,             # Batch size for training
    validation_split=0.2,      # Use 20% of the training data for validation
    verbose=1                  # Print progress
)

"""#Model Evaluation"""

# Evaluate the model on the test set
test_loss_3, test_acc_3 = model_with_l2.evaluate(test_data, test_labels)

print(f"Test Accuracy: {test_acc_3:.4f}")
print(f"Test Loss: {test_loss_3:.4f}")

"""### Reduce the Model Complexity

Overly complex models are more prone to **overfitting**, as they tend to memorize training data rather than generalize to new data. To address this, we reduce the model complexity by:
- **Reducing the number of LSTM units**: Decreasing the number of units from 128 to **64**. This helps the model learn simpler patterns, making it less likely to overfit.
- **Adjusting Dense layers**: Removing or reducing Dense layers can also limit the model’s capacity, improving generalization.

These changes aim to create a simpler, more generalizable model that performs better on unseen data.

"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, GlobalMaxPooling1D, Dense, Dropout

# Build the model with reduced complexity and Bidirectional LSTM
model_less_complex = Sequential([
    Embedding(input_dim=max_words,
              output_dim=embedding_dim,
              input_length=max_len),
    Bidirectional(LSTM(64, return_sequences=True)),  # Bidirectional LSTM with 64 units
    GlobalMaxPooling1D(),  # Global max pooling layer
    Dense(64, activation='relu'),  # Dense layer
    Dropout(0.5),  # Dropout for regularization
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model_less_complex.compile(optimizer='adam',
                                         loss='binary_crossentropy',
                                         metrics=['accuracy'])

# Print model summary
model_less_complex.summary()

"""Train the Model"""

# Train the model
history = model_less_complex.fit(
    train_data, train_labels,  # Training data and labels
    epochs=10,                  # Number of epochs to train for
    batch_size=64,             # Batch size for training
    validation_split=0.2,      # Use 20% of the training data for validation
    verbose=1                  # Print progress
)

"""Evaluation

"""

# Evaluate the model on the test set
test_loss_4, test_acc_4 = model_less_complex.evaluate(test_data, test_labels)

print(f"Test Accuracy: {test_acc_4:.4f}")
print(f"Test Loss: {test_loss_4:.4f}")

"""### Model with Reduced Complexity Using Bidirectional LSTM

In this step, we define a model with a Bidirectional LSTM to enhance generalization while keeping it simple.

#### Key Changes:
- **Bidirectional LSTM with 32 Units**: Captures context from both directions with reduced complexity.
- **Global Max Pooling Layer**: Extracts significant features, reducing dimensionality.
- **Dense Layer**: A fully connected layer with 64 units and ReLU activation.
- **Dropout for Regularization**: A dropout layer (0.5) helps prevent overfitting.
- **Output Layer**: A single unit with sigmoid activation for binary classification.


"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, GlobalMaxPooling1D, Dense, Dropout

# Build the model with reduced complexity and Bidirectional LSTM
model_less_complex_2 = Sequential([
    Embedding(input_dim=max_words,
              output_dim=embedding_dim,
              input_length=max_len),
    Bidirectional(LSTM(32, return_sequences=True)),  # Bidirectional LSTM with 32 units
    GlobalMaxPooling1D(),  # Global max pooling layer
    Dense(64, activation='relu'),  # Dense layer
    Dropout(0.5),  # Dropout for regularization
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model_less_complex_2.compile(optimizer='adam',
                                           loss='binary_crossentropy',
                                           metrics=['accuracy'])

# Train the model
history = model_less_complex_2.fit(
    train_data, train_labels,  # Training data and labels
    epochs=10,                  # Number of epochs to train for
    batch_size=64,             # Batch size for training
    validation_split=0.2,      # Use 20% of the training data for validation
    verbose=1                  # Print progress
)

# Evaluate the model on the test set
test_loss_5, test_acc_5 = model_less_complex_2.evaluate(test_data, test_labels)

print(f"Test Accuracy: {test_acc_5:.4f}")
print(f"Test Loss: {test_loss_5:.4f}")

"""### Building a Model with Hyperparameter Tuning

In this step, we construct a model that incorporates hyperparameter tuning to optimize performance.

#### Key Changes:
- **Bidirectional LSTM with 64 Units**: The model employs a Bidirectional LSTM layer with **64 units**, allowing it to capture context from both directions in the text.
- **Global Max Pooling**: This layer reduces the output dimensionality by selecting the most significant features from the LSTM output.
- **Dense Layer**: A fully connected layer with 64 units and ReLU activation to process the pooled features.
- **Dropout for Regularization**: A dropout layer with a rate of 0.5 is included to help prevent overfitting.
- **Lower Learning Rate**: The model is compiled with the Adam optimizer, set to a lower learning rate of **0.0001**. This adjustment allows for more gradual convergence during training, which can lead to better performance.

"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, GlobalMaxPooling1D, Dense, Dropout

# Build the model with Bidirectional LSTM and hyperparameter tuning
model_less_complex_hpt = Sequential([
    Embedding(input_dim=max_words,
              output_dim=embedding_dim,
              input_length=max_len),
    Bidirectional(LSTM(64, return_sequences=True)),  # Bidirectional LSTM with 64 units
    GlobalMaxPooling1D(),  # Global max pooling layer
    Dense(64, activation='relu'),  # Dense layer
    Dropout(0.5),  # Dropout for regularization
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model with a lower learning rate
model_less_complex_hpt.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
                                             loss='binary_crossentropy',
                                             metrics=['accuracy'])

# Train the model
history = model_less_complex_hpt.fit(
    train_data, train_labels,  # Training data and labels
    epochs=10,                  # Number of epochs to train for
    batch_size=64,             # Batch size for training
    validation_split=0.2,      # Use 20% of the training data for validation
    verbose=1                  # Print progress
)

# Evaluate the model on the test set
test_loss_6, test_acc_6 = model_less_complex_hpt.evaluate(test_data, test_labels)

print(f"Test Accuracy: {test_acc_6:.4f}")
print(f"Test Loss: {test_loss_6:.4f}")

"""No considerable change here

**Diagram of Developped Final Model**
"""

# Generate and save the model architecture diagram
plot_model(model_less_complex, to_file='model2.png', show_shapes=True, show_layer_names=True)

# Display the diagram in the notebook
Image('model2.png')

"""**Perfomance Curves of final model**"""

# Plot the accuracy curves
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Plot the loss curves
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.show()

"""**Confusion Matrix**

### Confusion Matrix and Classification Report
A confusion matrix and classification report are generated to evaluate model performance:
- **Precision**: Ratio of correctly predicted positive observations to total predicted positives.
- **Recall**: Ratio of correctly predicted positive observations to actual positives.
- **F1-Score**: Harmonic mean of precision and recall, providing a balanced measure of model performance.
"""

import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

# Step 1: Get the predicted probabilities from the model
y_pred_probs_4 = model_less_complex.predict(test_data)

# Step 2: Convert predicted probabilities to binary class labels (using a threshold of 0.5)
y_pred_4 = (y_pred_probs_4 > 0.5).astype("int32")

# Step 3: Generate the confusion matrix
conf_matrix_4 = confusion_matrix(test_labels, y_pred_4)

# Step 4: Print the confusion matrix
print("Confusion Matrix for model_less_complex:")
print(conf_matrix_4)

# Step 5: Optionally, print a detailed classification report (precision, recall, f1-score)
print("\nClassification Report for model_less_complex:")
print(classification_report(test_labels, y_pred_4, target_names=['Negative', 'Positive']))

# Print Test Accuracy and Loss for reference
print(f"\nTest Accuracy: {test_acc_4:.4f}")
print(f"Test Loss: {test_loss_4:.4f}")

"""### **Discussion, Analysis and Justification**

**Observations:**

- **Training vs Validation Performance**:  
  There is a noticeable gap between the training accuracy (e.g., 89.58%) and the validation accuracy (e.g., 84.36%), indicating potential overfitting. This occurs when the model learns to memorize the training data rather than generalize effectively to unseen data.

- **Test Set Performance**:  
  The model achieved a test accuracy of **88.98%**, which is strong for a sentiment classification task. The confusion matrix indicates balanced performance across both sentiment classes, reflecting effective classification capabilities.

- **Loss Behavior**:  
  Training loss consistently decreases (e.g., 0.3294), while fluctuations in validation loss suggest that the model may struggle to generalize well on unseen data. This discrepancy indicates that overfitting may still be a concern, necessitating further refinements.

- **Classification Metrics**:  
  The model demonstrates relatively high precision and recall for both classes. However, there is potential for improvement, especially in recall for the negative class (84%) and precision for the positive class (85%).

Overall, while the model exhibits solid performance, there remains room for enhancement in its ability to generalize and accurately classify sentiments, particularly for more nuanced or ambiguous reviews.

### Justifications for Model Choices:

**Bidirectional LSTM Layer:**
The Bidirectional LSTM was chosen to effectively capture context from both past and future sequences. This is particularly important for sentiment classification, as understanding the entire context of a sentence or review can significantly impact the model's ability to make accurate predictions.

**GlobalMaxPooling1D:**
This layer reduces the sequence length after the Bidirectional LSTM layer, selecting the most important features and simplifying the input for the subsequent dense layer. By focusing on salient features, it also helps mitigate overfitting, enhancing model generalization.

**Dropout Layer:**
Dropout is implemented for regularization to prevent overfitting. Given the model's high training accuracy, dropout layers are essential for ensuring that the model generalizes better to unseen data by randomly setting a portion of the inputs to zero during training.

**L2 Regularization:**
Incorporating L2 regularization in both the LSTM and Dense layers discourages the model from learning overly large weights. This helps prevent overfitting and promotes a more robust model by encouraging simpler representations.

**Adam Optimizer:**
The Adam optimizer is employed due to its adaptive learning rate capabilities, which allow for faster convergence and improved performance without requiring extensive manual tuning. This efficiency is critical for optimizing complex models in sentiment analysis.

#Limitations Of The Method

The training accuracy (98.28%) is much higher than the test accuracy (0.8898%), suggesting overfitting. Even though dropout was used to mitigate this, additional regularization techniques couldnt help further


**Faluire Cases**

Lets try analyze this by printing some false positives and false negatives.
"""

import numpy as np

# Step 1: Get the predicted probabilities from the enhanced model
y_pred_probs_enhanced = model.predict(test_data)

# Step 2: Convert predicted probabilities to binary class labels (using a threshold of 0.5)
y_pred_enhanced = (y_pred_probs_enhanced > 0.5).astype("int32").flatten()

# Step 3: Find false positives and false negatives
false_positives = np.where((y_pred_enhanced == 1) & (test_labels == 0))[0]  # Predicted positive, but actual negative
false_negatives = np.where((y_pred_enhanced == 0) & (test_labels == 1))[0]  # Predicted negative, but actual positive

# Function to filter reviews with less than 80 words
def filter_reviews_with_less_than_80_words(indices, reviews):
    return [i for i in indices if len(reviews[i].split()) < 80]

# Filter the false positives and false negatives
filtered_false_positives = filter_reviews_with_less_than_80_words(false_positives, test_texts)
filtered_false_negatives = filter_reviews_with_less_than_80_words(false_negatives, test_texts)

# Print examples of false positives and false negatives
print("\nFalse Positives (Predicted Positive, Actual Negative):")
for i in filtered_false_positives[:5]:  # Print first 5 false positives
    print(f"Review: {test_texts[i]}")
    print(f"Predicted Label: {y_pred_enhanced[i]}, Actual Label: {test_labels[i]}\n")

print("\nFalse Negatives (Predicted Negative, Actual Positive):")
for i in filtered_false_negatives[:5]:  # Print first 5 false negatives
    print(f"Review: {test_texts[i]}")
    print(f"Predicted Label: {y_pred_enhanced[i]}, Actual Label: {test_labels[i]}\n")

"""### Failure Case Analysis

The model achieves a good test accuracy (~0.8898%), but it faces limitations in specific cases:

1. **Negation Handling**:
   - Example: "If it wasn't for the terrific music, I would not hesitate to give this cinematic underachievement 2/10."
     - **Predicted**: Positive, **Actual**: Negative
   - The model struggles to interpret negations like "wasn't" and "would not," leading to incorrect predictions.

2. **Ambiguity in Sentiment**:
   - Example: "Mediocre at best. Slow, but probably more entertaining to the younger viewers."
     - **Predicted**: Positive, **Actual**: Negative
   - It misinterprets words like "entertaining," ignoring negative context words such as "mediocre."

3. **Sarcasm**:
   - Example: "Oh boy! It was just a dream! What a great idea!"
     - **Predicted**: Positive, **Actual**: Negative
   - The model takes literal phrases like "great idea" as positive without detecting the sarcastic tone.

4. **Complex Sentence Structures**:
   - Example: "The premise is rather original and well thought-of, but the low budget doesn't allow for decent special effects."
     - **Predicted**: Negative, **Actual**: Positive
   - It fails to capture the mixed sentiment and weighs negative phrases more heavily.

#### Limitations of the Model
- **Overfitting**: The model shows a gap between training and validation accuracy, indicating overfitting.
  - Possible Solution: Add more dropout or L2 regularization to improve generalization.
- **Contextual Understanding**: It struggles with long-range dependencies, leading to misclassifications in complex reviews.
  - Possible Solution: Use Bidirectional LSTMs or integrate pre-trained embeddings for better context handling.

In summary, the model performs well on straightforward reviews but struggles with negations, sarcasm, and complex sentence structures, highlighting the need for context-aware enhancements.

"""